---
name: Run benchmark

on:
  workflow_dispatch:
    inputs:
      starting_revision:
        description: >-
          The hash for the revision of glass-dev/glass to act as the starting
          state to be compared against.
        required: true
        default: main
        type: string
      end_revision:
        description: >-
          The hash for the revision of glass-dev/glass to act as the final
          state to be compared with the initial.
        required: true
        type: string

env:
  GLASS_REPO_URL: https://github.com/glass-dev/glass

jobs:
  regression-test:
    name: Regression test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache-dependency-path: pyproject.toml
          cache: pip
          python-version: ${{ matrix.python-version }}

      - name: Generate starting state benchmark
        run: >-
          python -m pip install . "git+$GLASS_REPO_URL@$STARTING_REVISION";
          python -m pytest --benchmark-autosave
        env:
          STARTING_REVISION: ${{ inputs.starting_revision }}

      - name: Run regression test
        run: >-
          python -m pip install . "git+$GLASS_REPO_URL@$END_REVISION";
          python -m pytest --benchmark-compare=0001
          --benchmark-compare-fail=min:5%
        env:
          END_REVISION: ${{ inputs.end_revision }}
